# Generated by Django 4.2.7 on 2025-09-28 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the schedule')),
                ('start_time', models.TimeField(help_text='Start time of the schedule')),
                ('end_date', models.DateField(help_text='End date of the schedule')),
                ('end_time', models.TimeField(help_text='End time of the schedule')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modified', 'Modified')], default='draft', help_text='Current status of the schedule', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the schedule was submitted for approval', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the schedule was approved', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Supervisor who approved the schedule', limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schedules', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Client for the schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clients.client')),
                ('employee', models.ForeignKey(help_text='Employee who created the schedule', limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('employee_overlap', 'Employee Time Overlap'), ('client_overlap', 'Client Time Overlap'), ('insufficient_gap', 'Insufficient Gap Between Schedules')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conflicting_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicted_by', to='schedules.schedule')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='schedules.schedule')),
            ],
            options={
                'db_table': 'schedule_conflicts',
                'unique_together': {('schedule', 'conflicting_schedule')},
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['employee', 'start_date'], name='schedules_employe_9c2aca_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['client', 'start_date'], name='schedules_client__1b40e9_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status'], name='schedules_status_0e1604_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['start_date', 'end_date'], name='schedules_start_d_05ea08_idx'),
        ),
    ]
